### ISSUE TITLE
RATE_ONE_SHOT not working for LPS22

### ISSUE THREAD

**Issue by pomplesiegel** [adafruit/Adafruit_LPS2X#4]
Hello! Overall this sensor library has worked great for me in the past, but I am not seeing the correct behavior for LPS22_RATE_ONE_SHOT.  I believe it may have worked correctly with this in the past, so I'm wondering if a change in the underlying libraries this driver is built in have potentially altered this behavior? 

When set to that rate, the values (pressure and temperature) remain constant at what was the most recent value. Any ideas regarding how to fix this? 

Hardware
* Adafruit Feather M0

Library Versions 
* Adafruit_LPS2X v2.0.1
* Adafruit_BusIO v1.11.4
* Adafruit_Sensor v1.1.5

Thank you!

**Comment by pomplesiegel** [comment]
@adafruit-adabot @ladyada, any thoughts on this? Thank you very much for your help!

**Comment by ladyada** [comment]
could be, if you figure out why or a fix please submit a PR! we have no ETA on investigating it

**Comment by caternuson** [comment]
A simple-as-possible example sketch demonstrating the issue would also help.

**Comment by pomplesiegel** [comment]
Sure! Thank you all for your help. 

Sketch to reproduce issue (started with the LPS22 example code, changed to use ONE_SHOT mode): 

````cpp
// Basic demo for pressure readings from Adafruit LPS2X - modified to test "one shot" mode
#include <Wire.h>
#include <Adafruit_LPS2X.h>
#include <Adafruit_Sensor.h>

Adafruit_LPS22 lps;

void setup(void) {
  Serial.begin(115200);
  delay(2000); 

  Serial.println("Adafruit LPS22 test!");

  // Try to initialize!
  if (!lps.begin_I2C()) {
    Serial.println("Failed to find LPS22 chip");
    while (1) { delay(10); }
  }
  Serial.println("LPS22 Found!");

  lps.setDataRate(LPS22_RATE_ONE_SHOT); //change value here!
  
  Serial.print("Data rate set to: ");
  switch (lps.getDataRate()) {
    case LPS22_RATE_ONE_SHOT: Serial.println("One Shot / Power Down"); break;
    case LPS22_RATE_1_HZ: Serial.println("1 Hz"); break;
    case LPS22_RATE_10_HZ: Serial.println("10 Hz"); break;
    case LPS22_RATE_25_HZ: Serial.println("25 Hz"); break;
    case LPS22_RATE_50_HZ: Serial.println("50 Hz"); break;

  }
}

void loop() {
  sensors_event_t temp;
  sensors_event_t pressure;
  lps.getEvent(&pressure, &temp);// get pressure
  Serial.print("Temperature: ");Serial.print(temp.temperature);Serial.println(" degrees C");
  Serial.print("Pressure: ");Serial.print(pressure.pressure);Serial.println(" hPa");
  Serial.println("");
  delay(1000);
}
````

Serial output when in ONE_SHOT mode (the values remain constant and never change): 

````
Adafruit LPS22 test!
LPS22 Found!
Data rate set to: One Shot / Power Down
Temperature: 16.27 degrees C
Pressure: 1020.90 hPa

Temperature: 16.27 degrees C
Pressure: 1020.90 hPa

Temperature: 16.27 degrees C
Pressure: 1020.90 hPa

Temperature: 16.27 degrees C
Pressure: 1020.90 hPa

Temperature: 16.27 degrees C
Pressure: 1020.90 hPa

Temperature: 16.27 degrees C
Pressure: 1020.90 hPa

Temperature: 16.27 degrees C
Pressure: 1020.90 hPa

Temperature: 16.27 degrees C
Pressure: 1020.90 hPa

Temperature: 16.27 degrees C
Pressure: 1020.90 hPa

Temperature: 16.27 degrees C
Pressure: 1020.90 hPa

Temperature: 16.27 degrees C
Pressure: 1020.90 hPa
````

Proper serial output and behavior, just by changing  the line `lps.setDataRate(LPS22_RATE_ONE_SHOT);` to any other value, such as `lps.setDataRate(LPS22_RATE_1_HZ);`: 

````
Adafruit LPS22 test!
LPS22 Found!
Data rate set to: 1 Hz
Temperature: 16.27 degrees C
Pressure: 1020.90 hPa

Temperature: 20.69 degrees C
Pressure: 1020.73 hPa

Temperature: 20.66 degrees C
Pressure: 1020.74 hPa

Temperature: 20.66 degrees C
Pressure: 1020.76 hPa

Temperature: 20.65 degrees C
Pressure: 1020.75 hPa

Temperature: 20.66 degrees C
Pressure: 1020.77 hPa

Temperature: 20.66 degrees C
Pressure: 1020.76 hPa

Temperature: 20.65 degrees C
Pressure: 1020.75 hPa

Temperature: 20.63 degrees C
Pressure: 1020.74 hPa

Temperature: 20.65 degrees C
Pressure: 1020.76 hPa

Temperature: 20.64 degrees C
Pressure: 1020.74 hPa

Temperature: 20.65 degrees C
Pressure: 1020.76 hPa
````
Notice that the values are now changing over time instead of just remaining constant. 

Any ideas? Thank you!

**Comment by caternuson** [comment]
Thanks for the example. Looks like a simple issue. One-shot mode just requires some extra handling. Submitted a potential fix with #5.

**Comment by pomplesiegel** [comment]
Great, thank you! I'll give this a test today and report back.

**Comment by caternuson** [comment]
This fix is in the 2.0.2 release:
https://github.com/adafruit/Adafruit_LPS2X/releases/tag/2.0.2

**Comment by pomplesiegel** [comment]
Just tested and this works great for me! 

One small thing - in `Adafruit_LPS25::setDataRate()` I believe 
`isOneShot = (new_data_rate == LPS22_RATE_ONE_SHOT) ? true : false;`
should be changed to 
`isOneShot = (new_data_rate == LPS25_RATE_ONE_SHOT) ? true : false;`

However, the issue I described is closed. Thank you!

**Comment by caternuson** [comment]
Yah...that's copy pasta :( My bad. Saw that too right after committing the merge. It'll end up working since both have the same actual value. But should get changed at some point.

Glad the fix worked. Thanks for testing and confirming.

**Comment by pomplesiegel** [comment]
Absolutely, thank you!
